//! Tray icon: builds the tray, swaps the status icon variants at runtime
//! (worst-of aggregate, SPEC R-2.6 + §43 blue waiting-workflow), and routes
//! left-click to the popup.
//!
//! Filled in by T3. (T0 keeps a minimal inline tray in `lib.rs`; T7 swaps that
//! placeholder for [`build`] + [`update`] during composition.)

use tauri::image::Image;
use tauri::menu::{Menu, MenuItem};
use tauri::tray::{MouseButton, MouseButtonState, TrayIcon, TrayIconBuilder, TrayIconEvent};
use tauri::AppHandle;

use crate::ipc::Counts;
use crate::windows;

/// Id of the single tray icon Quarterdeck runs.
pub const TRAY_ID: &str = "quarterdeck-tray";

/// Menu id of the tray "Quit Quarterdeck" item.
const QUIT_MENU_ID: &str = "quarterdeck-quit";

/// Worst-of aggregate tray status (SPEC §1, R-2.6 + §43): red > yellow > blue >
/// green > gray. Gray also covers "no sessions" and "sessions exist but all are
/// dead" — both read as "nothing needs you right now".
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TrayStatus {
    /// At least one session is blocked on the human (red).
    Attention,
    /// At least one session is executing a turn (yellow).
    Working,
    /// §43: at least one session's parent turn ended but background
    /// subagents/workflows are still running (blue).
    Waiting,
    /// At least one session is idle, awaiting instructions (green).
    Idle,
    /// No sessions, or only dead ones (gray).
    Gray,
}

impl TrayStatus {
    /// Computes the aggregate status from footer counts (SPEC R-2.6 + §43).
    pub fn worst_of(counts: &Counts) -> Self {
        if counts.attention > 0 {
            Self::Attention
        } else if counts.working > 0 {
            Self::Working
        } else if counts.waiting > 0 {
            Self::Waiting
        } else if counts.idle > 0 {
            Self::Idle
        } else {
            Self::Gray
        }
    }

    /// Stable lowercase name for the E2E test hook / logs.
    fn as_str(self) -> &'static str {
        match self {
            Self::Attention => "attention",
            Self::Working => "working",
            Self::Waiting => "waiting",
            Self::Idle => "idle",
            Self::Gray => "gray",
        }
    }

    /// The bundled 32px tray icon for this status (`assets/tray/*-32.png`,
    /// generated by T0's `scripts/gen-icons.mjs`).
    fn icon(self) -> Image<'static> {
        match self {
            Self::Attention => tauri::include_image!("../assets/tray/red-32.png"),
            Self::Working => tauri::include_image!("../assets/tray/yellow-32.png"),
            Self::Waiting => tauri::include_image!("../assets/tray/blue-32.png"),
            Self::Idle => tauri::include_image!("../assets/tray/green-32.png"),
            Self::Gray => tauri::include_image!("../assets/tray/gray-32.png"),
        }
    }
}

/// Builds the tray icon (initial neutral/gray, SPEC R-2.6) and wires
/// left-click to toggle the popup anchored to the tray (SPEC R-7.1). Called
/// once at startup by T7's composition in `lib.rs`; icon/tooltip updates
/// afterwards go through [`update`].
pub fn build(app: &AppHandle) -> tauri::Result<TrayIcon> {
    // Right-click context menu with an explicit Quit (critical): the popup/ask
    // WebView2 windows share one machine-global user-data profile
    // (`%LOCALAPPDATA%\pro.philippgross.quarterdeck\EBWebView`, one browser
    // process per profile). Without an in-app Quit, a user who wants to restart
    // Quarterdeck can only kill it from Task Manager — and an immediate relaunch
    // races that still-exiting WebView2 process ("The requested resource is in
    // use", 0x800700AA), leaving both windows permanently uncreatable and the
    // tray silently dead. `app.exit(0)` shuts the app down cleanly so WebView2
    // releases the profile before any relaunch. (The single-instance guard in
    // `lib.rs` already prevents the concurrent-launch variant.)
    let quit = MenuItem::with_id(app, QUIT_MENU_ID, "Quit Quarterdeck", true, None::<&str>)?;
    let menu = Menu::with_items(app, &[&quit])?;

    TrayIconBuilder::with_id(TRAY_ID)
        .icon(TrayStatus::Gray.icon())
        .tooltip(tooltip_for(&Counts::default()))
        .menu(&menu)
        // Left-click still toggles the popup (below); the menu is right-click only.
        .show_menu_on_left_click(false)
        .on_menu_event(|app, event| {
            if event.id.as_ref() == QUIT_MENU_ID {
                tracing::info!("quit requested from tray menu");
                app.exit(0);
            }
        })
        .on_tray_icon_event(|tray, event| {
            if let TrayIconEvent::Click {
                button: MouseButton::Left,
                button_state: MouseButtonState::Up,
                rect,
                ..
            } = event
            {
                if let Err(err) = windows::toggle_popup(tray.app_handle(), rect) {
                    tracing::warn!(error = %err, "failed to toggle popup from tray click");
                }
            }
        })
        .build(app)
}

/// Swaps the tray icon + tooltip to reflect `counts` (SPEC R-2.6, R-7.3).
/// Called by the engine's state-change handler (T7) after every
/// `deck://state` push.
pub fn update(tray: &TrayIcon, counts: &Counts) -> tauri::Result<()> {
    let status = TrayStatus::worst_of(counts);
    tray.set_icon(Some(status.icon()))?;
    record_tray_state_for_tests(status, counts);
    tray.set_tooltip(Some(tooltip_for(counts)))
}

/// E2E test hook (SPEC §11 "assert tray icon changes (via test hook)"): when the
/// fake-notifier mode is on (`QUARTERDECK_FAKE_NOTIFIER=1`, set only by the
/// isolated e2e harness — R-3.2), append the tray status just applied by
/// [`update`] to `<data>/tray-state.jsonl`. This lets the real-app smoke assert
/// the actual `TrayIcon::set_icon` swap ran with the worst-of status (R-2.6),
/// rather than only inferring it from the popup DOM. No-op in normal runs, so it
/// never touches a user's data dir.
fn record_tray_state_for_tests(status: TrayStatus, counts: &Counts) {
    if std::env::var("QUARTERDECK_FAKE_NOTIFIER").ok().as_deref() != Some("1") {
        return;
    }
    let dir = crate::settings::data_dir();
    if std::fs::create_dir_all(&dir).is_err() {
        return;
    }
    let at_ms = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis())
        .unwrap_or(0);
    let record = serde_json::json!({
        "v": 1,
        "atMs": at_ms,
        "status": status.as_str(),
        "counts": {
            "attention": counts.attention,
            "working": counts.working,
            "waiting": counts.waiting,
            "idle": counts.idle,
            "dead": counts.dead,
        },
    });
    if let Ok(mut file) = std::fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(dir.join("tray-state.jsonl"))
    {
        use std::io::Write;
        let _ = writeln!(file, "{record}");
    }
}

/// Tooltip text, mirroring the popup footer copy (SPEC R-7.3): e.g.
/// "Quarterdeck — 1 needs you · 2 working · 1 idle", or "Quarterdeck — no
/// sessions" when the fleet is empty.
pub fn tooltip_for(counts: &Counts) -> String {
    let total = counts.attention + counts.working + counts.waiting + counts.idle + counts.dead;
    if total == 0 {
        return "Quarterdeck — no sessions".to_string();
    }

    let mut parts = Vec::new();
    if counts.attention > 0 {
        parts.push(format!("{} needs you", counts.attention));
    }
    if counts.working > 0 {
        parts.push(format!("{} working", counts.working));
    }
    if counts.waiting > 0 {
        parts.push(format!("{} waiting", counts.waiting));
    }
    if counts.idle > 0 {
        parts.push(format!("{} idle", counts.idle));
    }
    if counts.dead > 0 {
        parts.push(format!("{} dead", counts.dead));
    }
    format!("Quarterdeck — {}", parts.join(" · "))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn worst_of_prefers_attention_over_everything() {
        let counts = Counts {
            attention: 1,
            working: 5,
            waiting: 5,
            idle: 5,
            dead: 5,
        };
        assert_eq!(TrayStatus::worst_of(&counts), TrayStatus::Attention);
    }

    #[test]
    fn worst_of_prefers_working_over_waiting_idle_and_dead() {
        let counts = Counts {
            attention: 0,
            working: 1,
            waiting: 5,
            idle: 5,
            dead: 5,
        };
        assert_eq!(TrayStatus::worst_of(&counts), TrayStatus::Working);
    }

    #[test]
    fn worst_of_prefers_waiting_over_idle_and_dead() {
        // §43: blue waiting-workflow outranks green idle in the tray worst-of.
        let counts = Counts {
            attention: 0,
            working: 0,
            waiting: 1,
            idle: 5,
            dead: 5,
        };
        assert_eq!(TrayStatus::worst_of(&counts), TrayStatus::Waiting);
    }

    #[test]
    fn worst_of_prefers_idle_over_dead() {
        let counts = Counts {
            attention: 0,
            working: 0,
            waiting: 0,
            idle: 1,
            dead: 5,
        };
        assert_eq!(TrayStatus::worst_of(&counts), TrayStatus::Idle);
    }

    #[test]
    fn worst_of_falls_back_to_gray_when_empty_or_all_dead() {
        assert_eq!(TrayStatus::worst_of(&Counts::default()), TrayStatus::Gray);
        assert_eq!(
            TrayStatus::worst_of(&Counts {
                dead: 3,
                ..Counts::default()
            }),
            TrayStatus::Gray
        );
    }

    #[test]
    fn tooltip_lists_nonzero_groups_in_status_order() {
        let counts = Counts {
            attention: 1,
            working: 2,
            waiting: 1,
            idle: 1,
            dead: 0,
        };
        assert_eq!(
            tooltip_for(&counts),
            "Quarterdeck — 1 needs you · 2 working · 1 waiting · 1 idle"
        );
    }

    #[test]
    fn tooltip_empty_state() {
        assert_eq!(tooltip_for(&Counts::default()), "Quarterdeck — no sessions");
    }

    #[test]
    fn tooltip_includes_dead_when_present() {
        let counts = Counts {
            dead: 2,
            ..Counts::default()
        };
        assert_eq!(tooltip_for(&counts), "Quarterdeck — 2 dead");
    }

    #[test]
    fn every_status_has_a_bundled_icon() {
        // include_image! fails at compile time if the asset is missing, but
        // exercise every variant so a future TrayStatus addition can't skip
        // wiring an icon.
        for status in [
            TrayStatus::Attention,
            TrayStatus::Working,
            TrayStatus::Waiting,
            TrayStatus::Idle,
            TrayStatus::Gray,
        ] {
            let _icon = status.icon();
        }
    }
}
